"""model modifications

Revision ID: 0d836765a5ef
Revises: 7939db168891
Create Date: 2025-05-20 14:04:19.787563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d836765a5ef'
down_revision: Union[str, None] = '7939db168891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('services', sa.Column('career_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'career_types', ['career_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'career_type_id')
    op.drop_column('services', 'currency')
    # ### end Alembic commands ###
