"""Add status and payment_status to bookings table

Revision ID: 41a1c39c4cb0
Revises: 5732d4679ce9
Create Date: 2025-05-14 16:53:15.037105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a1c39c4cb0'
down_revision: Union[str, None] = '5732d4679ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###
