"""Remove customer_name, provider_name, service_name from Booking

Revision ID: 9d27e90fce95
Revises: 3033b0ac7ece
Create Date: 2025-05-10 13:59:01.327788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d27e90fce95'
down_revision: Union[str, None] = '3033b0ac7ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('id', sa.Integer, primary_key=True, autoincrement=True))
    op.add_column('bookings', sa.Column('reminder_time', sa.DateTime(), nullable=True))
    op.alter_column('bookings', 'booking_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_bookings_booking_id', table_name='bookings')
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_column('bookings', 'booking_id')
    op.drop_column('bookings', 'service_details')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('service_details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('booking_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.create_index('ix_bookings_booking_id', 'bookings', ['booking_id'], unique=False)
    op.alter_column('bookings', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'provider_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'booking_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('bookings', 'reminder_time')
    op.drop_column('bookings', 'id')
    # ### end Alembic commands ###
